apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "danwiki.fullname" . }}-frontend
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "danwiki.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "danwiki.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: frontend
  template:
    metadata:
      labels:
        {{- include "danwiki.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: frontend
    spec:
      containers:
        - name: frontend
          image: "{{ .Values.image.repository }}/danwiki-frontend:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 80
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            {{- toYaml .Values.frontend.resources | nindent 12 }}
