apiVersion: v1
kind: Service
metadata:
  name: {{ include "danwiki.fullname" . }}-frontend
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "danwiki.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  selector:
    {{- include "danwiki.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
  ports:
    - port: 80
      targetPort: 80
