apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "danwiki.fullname" . }}-redis-data
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "danwiki.labels" . | nindent 4 }}
spec:
  storageClassName: {{ .Values.redis.storageClass }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.redis.storageSize }}
