"""Add is_approved field to User model for admin approval

Revision ID: 2c56258041a7
Revises: 7a20e2d1e99d
Create Date: 2026-01-20 23:35:12.373764

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c56258041a7'
down_revision = '7a20e2d1e99d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_approved', sa.Boolean(), nullable=True))
    
    # Set all existing users to approved
    op.execute("UPDATE users SET is_approved = TRUE WHERE is_approved IS NULL")
    
    # Make column non-nullable with default False
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('is_approved', nullable=False, server_default='false')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('is_approved')

    # ### end Alembic commands ###
