apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "danwiki.fullname" . }}-uploads
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "danwiki.labels" . | nindent 4 }}
spec:
  storageClassName: {{ .Values.uploads.storageClass }}
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.uploads.storageSize }}
